spring:
  main:
    allow-bean-definition-overriding: true
  batch:
#    jdbc:
#      initialize-schema: embedded
    job:
      names: helloJob
#      enabled: false

  jpa:
    show-sql: true
  datasource:
    jdbc-url: jdbc:h2:mem:testdb
  item-datasource:
    jdbc-url: jdbc:mysql://localhost:13306/customer?charactersetEncoding=UTF-8
    username: root

  flyway:
    user: root
    schemas: customer
    url: jdbc:mysql://localhost:13306/customer?charactersetEncoding=UTF-8
    enabled: true