spring:
  main:
    allow-bean-definition-overriding: true
  batch:
#    jdbc:
#      initialize-schema: embedded
    job:
      names: helloJob
#      enabled: false

  jpa:
    show-sql: true
  datasource:
    default:
      hikari:
        jdbc-url: jdbc:h2:mem:testdb
        maximum-pool-size: 5
        minimum-idle: 1
    item:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13306/customer?charactersetEncoding=UTF-8
        username: root

    seller:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13306/seller?charactersetEncoding=UTF-8
        username: root

  flyway:
    user: root
    schemas: customer
    url: jdbc:mysql://localhost:13306/customer?charactersetEncoding=UTF-8
    enabled: true